# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jin Young Kim's Homepage
email: lifidea@gmail.com
description: Jinyoung (Jin) Kim is a data scientist, data enthusiast and data evangelist. In Microsoft, he has tackled challenging measurement problems in the area of web and conversational search. In his free time, he collects and analyzes various types of data on and around him.
He has published more than a dozen papers in the area of information retrieval and data mining, and recently published a book titled ‘Hello, Data Science’’,  which became a national bestseller (#1 in technology category) in Korea with critical acclaim.
He has taught tutorials in evaluation and measurement of online services in both Microsoft and SIGIR, and consulted various teams in Microsoft on metric and experiment design. He has also served in program committees and organized workshops in SIGIR, WSDM, WWW, ECIR conferences.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lifidea
github_username:  jykim

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
